import CommentModel, { Comment } from '../models/commentModel';

class CommentService {
    // Create a new comment
    async createComment(articleId: number, authorId: number, content: string): Promise<Comment> {
        // Omit 'id' and 'created_at' from Comment as they are auto-generated by the database
        return await CommentModel.createComment({ article_id: articleId, author_id: authorId, content });
    }

    // Get comments for a specific article with pagination
    async getCommentsByArticleId(articleId: number, limit: number, offset: number): Promise<Comment[]> {
        return await CommentModel.getCommentsByArticleId(articleId, limit, offset);
    }
}

export default new CommentService();
